version: 2

builds:
  - main: ./cmd/lazyjira
    binary: lazyjira
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

nfpms:
  - package_name: lazyjira
    maintainer: "nikbrunner <https://github.com/nikbrunner>"
    homepage: "https://github.com/nikbrunner/lazyjira"
    description: "Terminal UI for Jira"
    license: MIT
    formats:
      - deb
      - rpm
      - apk

changelog:
  sort: asc

release:
  footer: |
    ---
    **Full changelog:**
    https://github.com/nikbrunner/lazyjira/blob/main/CHANGELOG.md
